### ISSUE TITLE
Git is broken

### ISSUE THREAD

**Issue by RDIL** [gosh-terminal/gosh#159]
https://asciinema.org/a/aLOne3iChte0Z6N8WDhWzQD1g

**Comment by RDIL** [comment]
@JesterOrNot I get the feeling this is an argument parsing issue

**Comment by JesterOrNot** [comment]
@RDIL is it ok that I assign you to this?

**Comment by RDIL** [comment]
I literally don't know go, I understand it but can't write it :(

**Comment by RDIL** [comment]
I can try but its very unlikely I'll be able to fix it

**Comment by JesterOrNot** [comment]
I got it then
